import os
import requests
from fastapi import FastAPI, HTTPException
from pydantic import BaseModel

app = FastAPI(title="Chat Vider Automation Core")

# ดึงค่าคีย์ความปลอดภัยจากระบบหลังบ้านแบบอัตโนมัติและถาวร
GITHUB_TOKEN = os.getenv("GITHUB_TOKEN")
RENDER_API_KEY = os.getenv("RENDER_API_KEY")
GITHUB_USERNAME = os.getenv("GITHUB_USERNAME", "your-github-username")

class DeployRequest(BaseModel):
    project_name: str
    prompt: str

@app.post("/api/v1/deploy/auto")
async def automated_deployment(data: DeployRequest):
    if not GITHUB_TOKEN or not RENDER_API_KEY:
        raise HTTPException(status_code=500, detail="Automation keys are not properly configured in environment variables.")
    
    # 1. สั่ง GitHub สร้าง Repository อัตโนมัติ
    gh_url = "https://api.github.com/user/repos"
    gh_headers = {
        "Authorization": f"Bearer {GITHUB_TOKEN}",
        "Accept": "application/vnd.github+json"
    }
    gh_payload = {
        "name": data.project_name,
        "private": False,
        "description": f"Auto-generated by Chat Vider. Prompt: {data.prompt}"
    }
    
    gh_response = requests.post(gh_url, json=gh_payload, headers=gh_headers)
    if gh_response.status_code != 201:
        raise HTTPException(status_code=400, detail="Failed to create GitHub repository.")
    
    repo_data = gh_response.json()
    repo_html_url = repo_data.get("html_url")
    
    # 2. (จำลองระบบต่อเนื่อง) ส่งสัญญาณต่อให้ Render หรือระบบ Cloud เพื่อ Deploy ทันที
    # ระบบจะทำการเชื่อมโยง GitHub Repo เข้ากับ Render Service อัตโนมัติ
    
    return {
        "status": "success",
        "message": "สร้างโปรเจกต์และเชื่อมต่อระบบ Cloud อัตโนมัติสำเร็จ",
        "github_repository": repo_html_url,
        "deployment_status": "Deploying to cloud..."
    }
